# Generated by Django 4.0.8 on 2023-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cource_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cource',
            new_name='Course',
        ),
    ]
